# Generated by Django 5.1.5 on 2025-02-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='add_time',
        ),
    ]
